import { startWorkerHealthServer } from "../utilities/workerHealthServer.ts";
import { verifyEnv } from "../utilities/config.ts";
import { startDisruptionTimeoutJob, stopDisruptionTimeoutJob, getDisruptionTimeoutProgress } from "../jobs/disruptionTimeoutJob.ts";
verifyEnv();
await import("../db.ts");
const interval = Number(process.env.DISRUPTION_TIMEOUT_SWEEP_INTERVAL_MS || 300_000);
if (!Number.isFinite(interval) || interval < 1000) throw new Error('Invalid disruption sweep interval');
startDisruptionTimeoutJob(interval);
const health = startWorkerHealthServer({ workerName: 'disruptionTimeoutWorker', defaultPort: 5003, onProgress: getDisruptionTimeoutProgress });
const shutdown = async () => { await stopDisruptionTimeoutJob(); await health.stop(); process.exit(0); };
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
